{
  "errors": {
    "didnt_block": "Вы ранее не блокировали ни одного пользователя/гильдии.",
    "didnt_block_user": "Вы не блокировали ни одного пользователя.",
    "didnt_block_guild": "Вы не блокировали ни одной гильдии.",
    "add": {
      "guild": "Произошла ошибка в добавлении гильдии в ваш список заблокированных, просим связаться с нами.",
      "user": {
        "none": "Пользователь не указан.",
        "self": "Глупышка, ты не можешь заблокировать самого себя.",
        "bot": "Вы не можете заблокировать бота.",
        "cantadd": "Произошла ошибка в добавлении пользователя в ваш список заблокированных, просим связаться с нами."
      }
    },
    "remove": {
      "guild": "Произошла ошибка в удалении гильдии из вашего списка заблокированных, просим связаться с нами.",
      "user": {
        "none": "Пользователь не указан.",
        "self": "Нельзя заблокировать/разблокировать себя, болван.",
        "bot": "Вы не можете заблокировать/разблокировать бота.",
        "cantremove": "Произошла ошибка в удалении пользователя из вашего списка заблокированных, просим связаться с нами."
      }
    },
    "cant_fetch": {
      "user": "Не удалось найти пользователя.",
      "guild": "Не удалось найти гильдию."
    }
  },
  "your_blocklist": "Черный список",
  "blocked": {
    "users": "Заблокированные Пользователи",
    "guilds": "Заблокированные Гильдии"
  },
  "add": {
    "guild": "Гильдия {{guildName}} занесена в черный список.",
    "user": "Пользователь {{userName}} занесен в черный список."
  },
  "remove": {
    "guild": "Гильдия {{guildName}} вынесена с черного списка.",
    "user": "Пользователь {{userName}} вынесен с черного списка."
  }
}
